CREATE TABLE `pay_order` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `order_id` varchar(64) DEFAULT NULL COMMENT '支付订单号',
    `order_type` int NOT NULL DEFAULT '0' COMMENT '订单类型 1-充值单，2-提款单，3-退款单，4-支付单',
    payment_type int NOT NULL DEFAULT '0' COMMENT '支付类型 1账号余额支付，2第三方渠道支付',
    `order_status` int DEFAULT '0' COMMENT '订单状态 0-待处理，1-成功，2-失败，3-手动取消，4-超时取消',
    `account_owner_id` bigint NOT NULL COMMENT '账户所属者ID',
    `account_owner_type` int NOT NULL COMMENT '账户所属者类型（0-会员，1-代理）',
    `account_id` bigint NOT NULL COMMENT '账户ID',
    `currency` varchar(8) NOT NULL COMMENT '交易币种',
    `amount` DECIMAL(20, 8) NOT NULL COMMENT '交易金额',
    `bonus_amount` DECIMAL(20, 8) NOT NULL COMMENT '赠送金额',
    `package_id` bigint NOT NULL '充值套餐编号',
    `fee_coupon_id` bigint NULL DEFAULT NULL COMMENT '手续优惠劵ID',
    `fee_discount_percent` decimal(20, 8) DEFAULT NULL COMMENT '手续折扣百分比',
    `fee_discount_amount` decimal(20, 8) DEFAULT NULL COMMENT '手续优惠金额(商户承担)',
    `remark` varchar(64) NOT NULL COMMENT '交易备注',
    `pay_settlement_amount` DECIMAL(20, 8) NOT NULL COMMENT '支付结算金额(第三方支付渠道)',
    `pay_fee_amount` DECIMAL(20, 8) NOT NULL COMMENT '支付手续费(第三方支付渠道)',
    `actual_amount` DECIMAL(20, 8) NOT NULL COMMENT '用户实际到账金额(支付结算金额+手续优惠金额+赠送金额)',
    `merchant_id` bigint default 0 not null comment '商户ID',
    `pay_channel_id` bigint DEFAULT NULL COMMENT '支付渠道ID',
    `reference_id` varchar(64) DEFAULT NULL COMMENT '第三方支付渠道订单号',
    `pay_url` varchar(256) DEFAULT NULL COMMENT '支付链接',
    `channel_result` varchar(256) DEFAULT NULL COMMENT '创建支付链接支付渠道返回结果',
    `order_expired_at` datetime DEFAULT NULL COMMENT '订单过期时间',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    unique `uniq_order_id` (`order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '支付订单表';

CREATE TABLE `deposit_order` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `order_id` varchar(64) DEFAULT NULL COMMENT '充值订单号',
    `order_status` int DEFAULT '0' COMMENT '订单状态 0-待处理，1-已支付，3-已入账，3-手动取消，4-超时取消',
    `merchant_id` varchar(64) default 0 not null comment '商户ID',
    `wallet_owner_id` varchar(64) NOT NULL COMMENT '钱包所属者ID',
    `wallet_owner_type` varchar(64) NOT NULL COMMENT '钱包所属者类型（0-会员，1-代理）',
    `wallet_id` varchar(64) NOT NULL COMMENT '钱包ID',
    `currency` varchar(8) NOT NULL COMMENT '交易币种',
    `amount` DECIMAL(38, 18) NOT NULL COMMENT '交易金额',
    `remark` varchar(64) NOT NULL COMMENT '交易备注',
    `order_paid_at` datetime DEFAULT NULL COMMENT '订单支付时间',
    `order_expired_at` datetime DEFAULT NULL COMMENT '订单过期时间',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    unique `uniq_order_id` (`order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '充值订单表';

CREATE TABLE `withdraw_order` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `order_id` varchar(64) DEFAULT NULL COMMENT '提款订单号',
    `order_status` int DEFAULT '0' COMMENT '订单状态 0-待处理，1-成功，2-失败，3-手动取消，4-超时取消',
    `merchant_id` varchar(64) default 0 not null comment '商户ID',
    `wallet_owner_id` varchar(64) NOT NULL COMMENT '钱包所属者ID',
    `wallet_owner_type` int NOT NULL COMMENT '钱包所属者类型（0-会员，1-代理）',
    `wallet_id` varchar(64) NOT NULL COMMENT '钱包ID',
    `currency` varchar(8) NOT NULL COMMENT '交易币种',
    `amount` DECIMAL(38, 18) NOT NULL COMMENT '交易金额',
    `payee_type` int NOT NULL COMMENT '收款账号类型 1bank，2alipay，3wechatpay，4USDT',
    `payee_name` varchar(64) DEFAULT NULL COMMENT '收款人名称',
    `payee_no` varchar(128) DEFAULT NULL COMMENT '收款人账号',
    `payee_org_name` varchar(128) DEFAULT NULL COMMENT '机构名称（银行）',
    `payee_org_no` varchar(128) DEFAULT NULL COMMENT '机构代码（银行代码）',
    `remark` varchar(64) NOT NULL COMMENT '交易备注',
    `real_amount` DECIMAL(38, 18) NOT NULL COMMENT '实际到账金额',
    `actual_at` datetime(3) DEFAULT NULL COMMENT '实际到账时间',
    `fee_amount` DECIMAL(38, 18) NOT NULL COMMENT '手续费',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    unique `uniq_order_id` (`order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '提款订单表';

CREATE TABLE `pay_transaction` (
    `id` bigint NOT NULL AUTO_INCREMENT,
    `trans_id` varchar(64) DEFAULT NULL COMMENT '交易号',
    `merchant_id` bigint default 0 not null comment '商户ID',
    `order_id` varchar(64) DEFAULT NULL COMMENT '订单号',
    `order_type` int NOT NULL DEFAULT '0' COMMENT '订单类型 1-充值单，2-提款单，3-退款单，4-支付单',
    `payment_type` int NOT NULL DEFAULT '0' COMMENT '支付类型 1账号余额支付，2第三方渠道支付,3优惠券',
    `trans_status` int DEFAULT '0' COMMENT '交易状态 0-待处理，1-成功，2-失败，3-退款',
    `currency` varchar(8) NOT NULL COMMENT '币种',
    `amount` DECIMAL(38, 18) NOT NULL COMMENT '金额',
    `actual_amount` DECIMAL(38, 18) NOT NULL COMMENT '实际金额',
    `fee_amount` DECIMAL(38, 18) NOT NULL COMMENT '手续费',
    `reference_id` varchar(64) DEFAULT NULL COMMENT '参考号(第三方支付单号，优惠券ID)',
    `create_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `update_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`),
    unique `uniq_order_id` (`order_id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 comment '支付交易表';