CREATE TABLE `trade_order` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_id` varchar(64) NOT NULL COMMENT '交易订单号',
    `merchant_id` varchar(64) NOT NULL COMMENT '商户ID',
    `agent_id` varchar(64) NOT NULL COMMENT '代理ID',
    `user_id` varchar(64) NOT NULL COMMENT '用户编号',
    `source_type` int NOT NULL COMMENT '订单来源类型(0-web,1-h5,2-app,3-third)',
    `status` int NOT NULL DEFAULT 0 COMMENT '订单状态',
    `remark` varchar(128) NULL DEFAULT NULL COMMENT '备注',
    `finish_time` datetime NULL DEFAULT NULL COMMENT '订单完成时间',
    `currency` varchar(32) NOT NULL DEFAULT '' COMMENT '币种',
    `amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '交易金额',
    `coupon_id` varchar(64) NULL DEFAULT NULL COMMENT '优惠劵编号',
    `coupon_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '优惠券金额',
    `coupon_currency` varchar(32) NOT NULL DEFAULT '' COMMENT '优惠券币种',
    `cancel_time` datetime NULL DEFAULT NULL COMMENT '取消时间',
    `cancel_reason` varchar(64) NOT NULL DEFAULT '' COMMENT '取消原因',
    `pay_order_id` varchar(64) NULL DEFAULT NULL COMMENT '支付订单编号',
    `pay_status` int NOT NULL DEFAULT 0 COMMENT '是否已支付：[0:未支付 1:已经支付]',
    `pay_time` datetime NULL DEFAULT NULL COMMENT '支付时间',
    `pay_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '实际支付金额(订单金额-优惠券金额)',
    `refund_order_id` varchar(64) NULL DEFAULT NULL COMMENT '退款订单编号',
    `refund_status` tinyint NOT NULL DEFAULT 0 COMMENT '退款状态',
    `refund_time` datetime NULL DEFAULT NULL COMMENT '退款时间',
    `refund_reason` varchar(128) NOT NULL DEFAULT '' COMMENT '退款原因',
    `refund_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '退款金额',
    `created_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `updated_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COMMENT = '交易订单表';

CREATE TABLE `trade_order_game_detail` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_id` varchar(64) NOT NULL COMMENT '交易订单号',
    `merchant_id` varchar(64) NOT NULL COMMENT '商户ID',
    `agent_id` varchar(64) NOT NULL COMMENT '代理ID',
    `user_id` varchar(64) NOT NULL COMMENT '用户编号',
    `game_category_id` int NOT NULL COMMENT '分类ID',
    `game_category_name` varchar(64) NOT NULL COMMENT '分类名称',
    `game_category_code` varchar(64) NOT NULL COMMENT '分类代码',
    `game_id` int NOT NULL COMMENT '游戏ID',
    `game_name` varchar(64) NOT NULL COMMENT '游戏名称',
    `game_code` varchar(64) NOT NULL COMMENT '游戏代码',
    `game_snapshot` varchar(1024) DEFAULT NULL COMMENT '游戏快照',
    `created_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `updated_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COMMENT = '交易订单游戏明细表';

CREATE TABLE `trade_order_coupon_detail` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_id` varchar(64) NOT NULL COMMENT '交易订单号',
    `merchant_id` varchar(64) NOT NULL COMMENT '商户ID',
    `agent_id` varchar(64) NOT NULL COMMENT '代理ID',
    `user_id` varchar(64) NOT NULL COMMENT '用户编号',
    `coupon_id` varchar(64) NULL DEFAULT NULL COMMENT '优惠劵编号',
    `coupon_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '优惠券金额',
    `coupon_currency` varchar(32) NOT NULL DEFAULT '' COMMENT '优惠券币种',
    `coupon_snapshot` varchar(512) DEFAULT NULL COMMENT '优惠券快照',
    `created_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `updated_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COMMENT = '交易订单优惠劵明细表';

CREATE TABLE `trade_order_settlement` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_id` varchar(64) NOT NULL COMMENT '交易订单号',
    `merchant_id` varchar(64) NOT NULL COMMENT '商户ID',
    `agent_id` varchar(64) NOT NULL COMMENT '代理ID',
    `user_id` varchar(64) NOT NULL COMMENT '用户编号',
    `order_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '订单金额',
    `order_currency` varchar(32) NOT NULL DEFAULT '' COMMENT '订单币种',
    `coupon_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '优惠券金额',
    `coupon_currency` varchar(32) NOT NULL DEFAULT '' COMMENT '优惠券币种',
    `game_odds` decimal(20, 8) NOT NULL COMMENT '游戏赔率',
    `cashback_rate` decimal(20, 8) NOT NULL COMMENT '返还比例',
    `cashback_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '返还金额(订单金额*返还比例)',
    `cashback_currency` varchar(32) NOT NULL DEFAULT '' COMMENT '返还币种',
    `settlement_status` int NOT NULL DEFAULT 0 COMMENT '结算状态',
    `settlement_amount` decimal(20, 8) NOT NULL DEFAULT '0.00000000' COMMENT '结算金额=订单金额*赔率',
    `settlement_currency` varchar(32) NOT NULL DEFAULT '' COMMENT '结算币种',
    `settlement_snapshot` varchar(1024) DEFAULT NULL COMMENT '结算快照',
    `trade_snapshot` varchar(1024) DEFAULT NULL COMMENT '交易快照',
    `created_by` varchar(64) DEFAULT NULL COMMENT '创建者',
    `updated_by` varchar(64) DEFAULT NULL COMMENT '更新者',
    `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最后更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COMMENT = '交易订单结算表';