package errcode

var (
	MerchantReqParamsErr             = New(101000, "merchant req params err")
	MerchantIdIsNull                 = New(101001, "merchant id is null")
	MerchantNameIsNull               = New(101002, "merchant name is null")
	MerchantPhoneIsNull              = New(101003, "merchant phone is null")
	MerchantEmailIsNull              = New(101004, "merchant email is null")
	MerchantAvatarIsNull             = New(101005, "merchant avatar is null")
	MerchantCreateErr                = New(101006, "merchant create err")
	MerchantExistsErr                = New(101007, "merchant already exists")
	MerchantNoFoundErr               = New(101008, "merchant no found")
	MerchantUpdateReqParamsErr       = New(101009, "merchant update req params err")
	MerchantUpdateErr                = New(101010, "merchant update err")
	MerchantCreateReqParamsErr       = New(101011, "merchant create req params err")
	MerchantUpdateStatusReqParamsErr = New(101012, "merchant update status req params err")
	MerchantUpdateStatusErr          = New(101013, "merchant update status err")
	MerchantNameExistsErr            = New(101014, "merchant name already exists")
	MerchantStatusNotActiveErr       = New(101015, "merchant status not active")
	MerchantStatusActiveErr          = New(101016, "merchant status active err")
	MerchantListErr                  = New(101017, "merchant list err")
	MerchantDomainIsNull             = New(101018, "merchant domain is null")
	MerchantDomainReqParamsErr       = New(101019, "merchant domain req params err")
	MerchantDomainExist              = New(101020, "merchant domain already exists")
	MerchantDomainSaveErr            = New(101021, "merchant domain save err")
	MerchantBaseSettingsErr          = New(101022, "merchant base settings err")
	MerchantGameSettingsErr          = New(101023, "merchant game settings err")
)
